### ISSUE TITLE
サンプルのattr指定ミスな気がします

### ISSUE THREAD

**Issue by bowyer-app** [fan-ADN/nendSDK-Android#1]
https://github.com/fan-ADN/nendSDK-Android/blob/99ad0b3a87fc8b0932be3774abf385d410ad3ea4/Sample/res/layout/icon_dialog.xml#L25

```
<net.nend.android.NendAdIconView 
        android:id="@+id/icon4" 
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        titleColor="#FFFFFF" />
```

上記コードだと、タイトルが白くなりませんでした。
正しくはNendTitleColorな気がしますがいかがでしょうか？

```
<net.nend.android.NendAdIconView 
        android:id="@+id/icon4" 
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        NendTitleColor="#FFFFFF" />
```

**Comment by fan-y-yamamoto** [comment]
bowyer-app様

ご連絡いただきありがとうございます。
株式会社ファンコミュニケーションズ山本と申します。

ご指摘の通り正しくはNendTitleColorになります。
サンプル内の誤った属性を指定している箇所を全て修正し、
次回SDKアップデートと同時にリリースさせていただきます。

今後ともnendをよろしくお願いいたします。

**Comment by fan-y-yamamoto** [comment]
bowyer-app様

ご指摘いただいておりました属性の修正を行いました。
ご連絡いただきありがとうございました。

今後ともnendをよろしくお願いいたします。

**Comment by bowyer-app** [comment]
@fan-y-yamamoto 様

わざわざご連絡ありがとうございます。
修正確認しました。
