### ISSUE TITLE
Flutter向けnative APIの追加

### ISSUE THREAD

**Issue by reedom** [fan-ADN/nendSDK-Android#10]
[Flutter][]ではiOS/Androidの標準Viewを使わずに独自のWidgetツリーで要素管理([1][], [2][])し、OpenGLで描画を行います。
そのためViewを要求とするNendSDK現行APIとは馴染みません。
（なおFlutterでもViewを扱うためのブリッジを用意していますが、いまのことろAndroidのみ、さらにその仕組み上動作は重いです）

[Appnext社iOS版SDK][]では低水準APIを提供しているため、Flutterでのnative広告埋め込みが可能です。
同様なAPIの追加を検討いただけないでしょうか。

[Flutter]: https://flutter.io/
[1]: https://flutter.io/docs/resources/technical-overview
[2]: https://speakerdeck.com/najeira/shi-zu-miwozhi-rebabu-kunai-flutterru-men
[Appnext社iOS版SDK]: https://developers.appnext.com/docs/appnext-ios-native-ads

**Comment by fan-t-fukuoka** [comment]
@reedom 様

お問い合わせ頂きありがとうございます。
現在、Flutterの対応を社内で検討しております。
機能を提供できるようになりましたら、改めてご案内させて頂きます。

今後ともよろしくお願いいたします。

**Comment by fan-t-fukuoka** [comment]
@reedom 様

[nend_plugin 0.0.3](https://pub.dev/packages/nend_plugin#-readme-tab-)でネイティブ広告用のAPIを追加しましたのでご案内させて頂きます。

現在ネイティブ広告用のAPIで対応しているのは静止画のみですが、動画ネイティブやフルボードなどのフォーマットの対応も今後予定しております。

今後も宜しくお願いいたします。

**Comment by reedom** [comment]
ご連絡ありがとうございます！
動作確認はまだですが、ソースを拝見したところ、希望通りの動作をしそうです。

HANAI Tohru <tohru@reedom.com>
