### ISSUE TITLE
NendAdNativeVideo Crash when OnStopVideo

### ISSUE THREAD

**Issue by jackyhieu1211-hn** [fan-ADN/nendSDK-Android#11]
java.lang.NullPointerException: Attempt to invoke virtual method 'int net.nend.android.internal.ui.views.video.NendAdVideoView.getCurrentPosition()' on a null object reference
        at net.nend.android.NendAdNativeMediaView$9.onClick(NendAdNativeMediaView.java:493)
        at android.view.View.performClick(View.java:6909)
        at android.view.View$PerformClick.run(View.java:26199)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Hello admin
- I using sample below
https://github.com/fan-ADN/nendSDK-Android/blob/master/Sample/java/src/main/java/net/nend/sample/java/nativeadvideo/RecyclerViewInFeedActivity.java
- When nativeVideo call onStopPlay. Video display background is only black. I click to it and I get error above. 

       nativeVideo.setMediaViewListener(object : NendAdNativeMediaViewListener{
                override fun onStopPlay(nendAd: NendAdNativeMediaView?) {
                    Timber.e("onStopPlay")
                }

                override fun onOpenFullScreen(p0: NendAdNativeMediaView?) {
                    Timber.e("onOpenFullScreen")
                }

                override fun onCloseFullScreen(p0: NendAdNativeMediaView?) {
                    Timber.e("onCloseFullScreen")
                }

                override fun onStartPlay(p0: NendAdNativeMediaView?) {
                    Timber.e("onStartPlay")
                }

                override fun onCompletePlay(p0: NendAdNativeMediaView?) {
                    Timber.e("onCompletePlay")
                }

                override fun onError(p0: Int, p1: String?) {
                   Timber.e("onError")
                }
            })
        }

Please help me fix it

**Comment by ghost** [comment]
Hi @jackyhieu 

Your log reports `NendAdNativeMediaView` was crashed when was clicked, but your code highlight doesn't have implementation about clicking.

So could you share us more information about:
* Please share your build project that could occurs this issue.
* Full adb log
* Your debug environment <- because Native-Video ad is only available in Japan
  * location or IP Address, or using VPN?

Thanks!

**Comment by jackyhieu1211-hn** [comment]
I copied all source at RecyclerViewInFeedActivity.java
I'm from Viet nam.
I use ID test
   api_key: a284d892c3617bf5705facd3bfd8e9934a8b2491
   spot_id: 887591
I do not implementation click event. I simply click on the video. When I scroll recyclerview. onStopPlay called. Video display background is only black. I click to it. App crash.

        override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {
        when (holder) {
            is SpaceViewHolder -> {
                holder.bind()
            }

            is AdsViewHolder -> {
                val loadedAd = videos.get(position)
                if (loadedAd != null) {
                    holder.bind(loadedAd)
                } else {
                    loader.loadAd(object : NendAdNativeVideoLoader.Callback {
                        override fun onSuccess(ad: NendAdNativeVideo?) {
                            context.runOnUiThread {
                                ad?.let {
                                    videos.put(holder.adapterPosition, ad)
                                    holder.bind(ad)
                                }
                            }
                        }

                        override fun onFailure(p0: Int) {

                        }
                    })
                }
            }

            is EmptyHolder -> {
                holder.bind(context, listener)
            }
        }


      class AdsViewHolder(override val containerView: View) : RecyclerView.ViewHolder(containerView), LayoutContainer {
        fun bind(ad: NendAdNativeVideo) {
            ad.isMutePlayingFullscreen = true
            nativeVideo.setMedia(ad)
            nativeVideo.setMediaViewListener(object : NendAdNativeMediaViewListener {
                override fun onStopPlay(nendAd: NendAdNativeMediaView?) {
                Timber.e("onStopPlay")
                }

                override fun onOpenFullScreen(p0: NendAdNativeMediaView?) {
                }

                override fun onCloseFullScreen(p0: NendAdNativeMediaView?) {
                }

                override fun onStartPlay(p0: NendAdNativeMediaView?) {
                }

                override fun onCompletePlay(p0: NendAdNativeMediaView?) {
                }

                override fun onError(p0: Int, p1: String?) {
                }
            })
        }

    }

**Comment by ghost** [comment]
@jackyhieu 

>I copied all source at RecyclerViewInFeedActivity.java

I think your copying implementation is not enough yet..
Our recycler view examples refill video media on scroll changed to `RecyclerView.SCROLL_STATE_IDLE` for performance optimization.

Your log tells your app seems to be not refill video media via `setMedia` to binding-view.

Please check our reference of Native-Video ad and `RecyclerView`, instead of copy-driven development.
https://github.com/fan-ADN/nendSDK-Android/wiki/Implementation-for-native-video-ads
https://developer.android.com/reference/android/support/v7/widget/RecyclerView

And also check our Kotlin examples because your app seems to look written by Kotlin, not Java.
https://github.com/fan-ADN/nendSDK-Android/tree/master/Sample/kotlin
