### ISSUE TITLE
動画リワード広告における位置情報の無効化方法

### ISSUE THREAD

**Issue by S64** [fan-ADN/nendSDK-Android#12]
現在Android向けnend SDK 5.1.0へのアップデートを検討しております。
バージョン5.1.0のリリースノートとして、

> - 位置情報を利用する広告に対して、広告ロード時に位置情報の利用有無を設定するオプションを追加

という文が記載されており、[動画広告実装手順](https://github.com/fan-ADN/nendSDK-Android/wiki/%E5%8B%95%E7%94%BB%E5%BA%83%E5%91%8A%E5%AE%9F%E8%A3%85%E6%89%8B%E9%A0%86/_compare/281afdfb6481b85dfe3649199c6151653216df5e...e4186c2376becf63f581e6bbb18dd27261755696)にもそれに伴う記載が追加されていることを確認しております。

この内 インタースティシャル広告における設定手順は内容のとおりかと存じておりますが、動画リワード広告における設定手順については インタースティシャル広告における設定手順へのリンクとなっており、動画リワード広告での手順が不明な状態となっておりました。

また、`NendAdRewardedVideo`のインスタンスにてpublicに設定されているメソッドをひととおり確認してみましたが、該当するメソッドは確認できませんでした。

以下の点につきまして、ご確認したく思います:

- 動画リワード広告における 位置情報利用の無効化は、現行バージョンにて可能でしょうか？
- 可能な場合、正しい手順をご教示頂くことは可能でしょうか？
- 不可能な場合、今後これらの機能が実装される可能性はございますでしょうか？

**Comment by fan-t-fukuoka** [comment]
@S64 様

お問い合わせ頂きありがとうございます。
設定手順で分かりづらい点がございまして申し訳ありません。

以下、お答えいたします。
> 動画リワード広告における 位置情報利用の無効化は、現行バージョンにて可能でしょうか？

可能でございます。

> 可能な場合、正しい手順をご教示頂くことは可能でしょうか？

動画インタースティシャルの[こちらの方法](https://github.com/fan-ADN/nendSDK-Android/wiki/動画広告実装手順#set_enabled_location) と同様に、`NendAdRewardedVideo`インスタンスにて`setLocationEnabled`メソッドを実装して頂くことが可能です。

以上、お手数ではございますが、よろしくお願いいたします。

**Comment by S64** [comment]
@fan-t-fukuoka さま、ご回答ありがとうございます。
おかげさまで問題が解決しましたので、ご報告致します。

> 動画インタースティシャルのこちらの方法 と同様に、NendAdRewardedVideoインスタンスにてsetLocationEnabledメソッドを実装して頂くことが可能です。

頂いた内容を元に試行したところ やはり当該メソッドが発見できませんでしたが、この結果を受けAndroid Studioの `Invalidate caches / Restart` を実行してみたところ、当該メソッドの存在を確認できるようになりました。

お手数おかけし申し訳ございませんでした。ありがとうございます。
