### ISSUE TITLE
Androidアプリ向け表示テスト用IDのネイティブ（Large-Wide）noapiKeyとspotIDが間違っている

### ISSUE THREAD

**Issue by kkkkan** [fan-ADN/nendSDK-Android#14]
Androidアプリ向け表示テスト用IDの「ネイティブ（Large-Wide）」のapiKeyとspotIDが、「フルボード」と全く同じになってしまっています。(日本語・英語・中国語全て)
また、このkey,idで読み込んでも表示できません。(nend SDK v8.0.1 + admob mediation adapter v8.0.1.0+admob sdk v20.4.0)
恐らく間違っていると思います。

ご確認お願いします。

https://github.com/fan-ADN/nendSDK-Android/wiki/%E3%83%86%E3%82%B9%E3%83%88%E8%A1%A8%E7%A4%BA%E3%82%92%E8%A1%8C%E3%81%86#android%E3%82%A2%E3%83%97%E3%83%AA%E5%90%91%E3%81%91%E8%A1%A8%E7%A4%BA%E3%83%86%E3%82%B9%E3%83%88%E7%94%A8id

https://github.com/fan-ADN/nendSDK-Android/wiki/Verification

https://github.com/fan-ADN/nendSDK-Android/wiki/%E8%BF%9B%E8%A1%8C%E6%B5%8B%E8%AF%95%E6%98%BE%E7%A4%BA

**Comment by nnsnico** [comment]
@kkkkan 様

お問い合わせいただきありがとうございます。

> Androidアプリ向け表示テスト用IDの「ネイティブ（Large-Wide）」のapiKeyとspotIDが、「フルボード」と全く同じになってしまっています。

こちらについてですが、nendではフルボード広告はネイティブ広告の一部として提供しております。そのため、wikiに掲載している広告IDとAPIKeyの組み合わせが同じであることで間違いありません。

> また、このkey,idで読み込んでも表示できません。

こちらについては同じ環境で動作可能か検証してみます。多少お時間いただくかもしれませんがご容赦ください。
つきましては詳しい事象を知りたいので、可能であれば以下をお教えいただけますでしょうか？
* 問題が起きた際のエラーログ
* 上記を確認できるサンプルコード(本番の広告ID及びAPIKeyを掲載しないようご注意ください)

以上、お手数おかけしますがよろしくお願い致します。

**Comment by kkkkan** [comment]
@nnsnico さま

お返事いただきありがとうございます。
>こちらについてですが、nendではフルボード広告はネイティブ広告の一部として提供しております。そのため、wikiに掲載している広告IDとAPIKeyの組み合わせが同じであることで間違いありません。

承知しました。
失礼いたしました。ご教授ありがとうございます。

> 問題が起きた際のエラーログ
上記を確認できるサンプルコード(本番の広告ID及びAPIKeyを掲載しないようご注意ください)

こちらですが、(こちらの事情となってしまうのですが)ちょっと状況が複雑ですぐに準備できるかわからないのですが、準備出来次第お送りさせていただこうと思います。

申し訳ございませんがよろしくお願いいたします。

**Comment by kkkkan** [comment]
@nnsnico さま

お世話になっております。

> 準備出来次第お送りさせていただこうと思います。
こちらの件ですが、シンプルなアプリを新規作成して試してみたところ再現させることができませんでした。

こちらの手違いもしくは何か別のところで間違えてしまっていたかもしれません。申し訳ございません。
いったんcloseさせていただいて、万が一再現条件を把握することができることがあったら再度ご連絡させていただきます。

**Comment by kkkkan** [comment]
@nnsnico さま

お世話になっております。

> 準備出来次第お送りさせていただこうと思います。
こちらの件ですが、シンプルなアプリを新規作成して試してみたところ再現させることができませんでした。
https://github.com/kkkkan/NendAdResearch

こちらの手違い、もしくは何か別のところで間違えてしまっていたかもしれません。申し訳ございません。
こちらのissueはいったんcloseさせていただいて、万が一今後再現条件を把握することができることがあったら再度ご連絡させていただきたいと思います。

お手数おかけしてしまったのに申し訳ないのですが、よろしくお願いいたします。

**Comment by nnsnico** [comment]
@kkkkan 様
ご連絡ありがとうございます。
本件、再現ができなかった旨承知いたしました。
こちらでも随時確認しておりますがまだ同様の再現ができるところまでは至っていませんので、確認の過程で事象が起きた際はこちらからこのissueにてご連絡させていただきます。
