### ISSUE TITLE
リソースの動的指定

### ISSUE THREAD

**Issue by sakebook** [fan-ADN/nendSDK-Android#2]
`xml`で、テスト用のIDと本番用のIDを動的に切り替えようとしてるのですが、
リソースでの指定には対応していないのでしょうか？
対応予定はありますか？

``` activity_hoge.xml
<net.nend.android.NendAdView
        android:id="@+id/nend"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        NendApiKey="@string/nend_api_key"
        NendSpotId="@integer/nend_id"
        android:layout_centerHorizontal="true"
        />
```
- error
  
  > Caused by: java.lang.NumberFormatException: Invalid int: "@integer/nend_id"

ご確認よろしくお願いします。

**Comment by ghost** [comment]
sakebook様

ご連絡いただきありがとうございます。
株式会社ファンコミュニケーションズ真鍋と申します。

申し訳ございませんが、現状のSDKはapiKeyおよびspotIdの
リソースファイルでの指定には対応しておりません。
こちらは次回のSDKのアップデートで対応させていただきたいと思います。
アップデート時期は年明けを予定しております。

今後ともnendをよろしくお願いいたします。

**Comment by sakebook** [comment]
早速の返信ありがとうございます。

> 申し訳ございませんが、現状のSDKはapiKeyおよびspotIdの
> リソースファイルでの指定には対応しておりません。
> こちらは次回のSDKのアップデートで対応させていただきたいと思います。
> アップデート時期は年明けを予定しております。

承知しました。
対応したバージョンのSDKが公開された際にコメントをいただけると幸いです。
よろしくお願いします。

**Comment by ghost** [comment]
sakebook様

お世話になっております。
株式会社ファンコミュニケーションズの逸見と申します。

ご要望いただきました機能につきまして、本日リリースのv3.0.4のSDKで対応いたしました。
是非、ご利用くださいませ。

使用方法については以下のマニュアルをご参照ください。
[バナー型広告_実装手順#レイアウトファイルで固定配置する場合](https://github.com/fan-ADN/nendSDK-Android/wiki/バナー型広告_実装手順#レイアウトファイルで固定配置する場合)

お待たせいたしまして申し訳ありませんでした。
今後ともnendをよろしくお願い致します。
