### ISSUE TITLE
gradleから過去バージョンのSDKが取得できない

### ISSUE THREAD

**Issue by bowyer-app** [fan-ADN/nendSDK-Android#3]
過去のバージョン

```
compile 'net.nend.android:nend-sdk:3.0.4'
```

が取得出来ません。
mavenのリポジトリから過去バージョンを取得することは出来ないでしょうか？

最新のSDK

```
compile 'net.nend.android:nend-sdk:3.0.5'
```

では

```
targetSdkVersion 23
```

https://github.com/fan-ADN/nendSDK-Android/blob/master/Sample/app/build.gradle#L10
を指定しないと使えないです。
プロジェクトによっては23サポートが出来ておらず上げられない場合もあると思いますので残していただきたいです。

**Comment by ghost** [comment]
@bowyer-app 様
株式会社ファンコミュニケーションズの逸見と申します。
ご連絡いただきありがとうございます。

> ```
> targetSdkVersion 23
> ```
> 
> https://github.com/fan-ADN/nendSDK-Android/blob/master/Sample/app/build.gradle#L10
> を指定しないと使えないです。
> プロジェクトによっては23サポートが出来ておらず上げられない場合もあると思いますので残してい>ただきたいです。

こちらの件ですが、build.gradeの設定はどのようにされていますでしょうか。
下記のようにtargetSdkVersionを下げ試した所、問題なくビルドできる事を確認いたしました。

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "net.nend.sample"
        minSdkVersion 10
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    maven {
        // nendSDK
        url 'http://fan-adn.github.io/nendSDK-Android-lib/library'
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.+'
    compile "com.android.support:cardview-v7:22.+"
    compile 'net.nend.android:nend-sdk:3.0.5'
}
```

一度同じようにお試しいただいてビルドできないようでしたら、build.gradleの記述内容、AndroidStudioのバージョンなどをお教えいただけると幸いです。

また、旧バージョンのSDKに関しましては、不具合修正なども含まれておりますので、最新版をご利用いただくようにお願いしております。

よろしくお願いいたします。

**Comment by bowyer-app** [comment]
@fan-t-henmi 様

お世話になります。
申し訳ありません、こちらの確認不備でした。

```
targetSdkVersion 23
```

こちらに関しては問題なくビルドできました。

> また、旧バージョンのSDKに関しましては、不具合修正なども含まれておりますので、最新版をご利用いただくようにお願いしております。

わかりました。ありがとうございます。
issue閉じさせていただきます。
