### ISSUE TITLE
Can not show ads

### ISSUE THREAD

**Issue by gmavenis** [fan-ADN/nendSDK-Android#4]
I add in xml layout:
<net.nend.android.NendAdView
                android:id="@+id/nend"
                NendAdjustSize="true"
                NendApiKey="c5cb8bc474345961c6e7a9778c947957ed8e1e4f"
                NendSpotId="3174"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal" />
If in basic Activity, it can be show.
But in me.tangke.slidemenu.SlideMenu, it can not show

**Comment by ghost** [comment]
@gmavenis 
Thank you for your inquiry.
How did you coding the XML file?
We could show banner ad by code below.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<me.tangke.slidemenu.SlideMenu 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:slidemenu="http://schemas.android.com/apk/res-auto"
    android:id="@+id/slideMenu"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    slidemenudemo:primaryShadowWidth="10dp"
    slidemenudemo:secondaryShadowWidth="10dp"
    slidemenudemo:slideDirection="left|right" >
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center|bottom"
        slidemenudemo:layout_role="content">
        <net.nend.android.NendAdView
            android:id="@+id/nend1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            NendAdjustSize="true"
            NendApiKey="c5cb8bc474345961c6e7a9778c947957ed8e1e4f"
            NendSpotId="3174" />
    </LinearLayout>
    <LinearLayout
        android:layout_width="200dip"
        android:layout_height="match_parent"
        android:gravity="center|bottom"
        slidemenudemo:layout_role="primaryMenu">
        <net.nend.android.NendAdView
            android:id="@+id/nend2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            NendAdjustSize="true"
            NendApiKey="c5cb8bc474345961c6e7a9778c947957ed8e1e4f"
            NendSpotId="3174" />
    </LinearLayout>
    <LinearLayout
        android:layout_width="300dip"
        android:layout_height="match_parent"
        android:gravity="center|bottom"
        slidemenudemo:layout_role="secondaryMenu">
        <net.nend.android.NendAdView
            android:id="@+id/nend3"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            NendAdjustSize="true"
            NendApiKey="c5cb8bc474345961c6e7a9778c947957ed8e1e4f"
            NendSpotId="3174" />
    </LinearLayout>
</me.tangke.slidemenu.SlideMenu>
```

<img src="https://cloud.githubusercontent.com/assets/16109689/17761585/3b9f3a14-6543-11e6-98c5-47b5efd52c53.png" width="300px">

<img src="https://cloud.githubusercontent.com/assets/16109689/17761654/d74e00a8-6543-11e6-88c7-2486bcfcb208.png" width="300px">

**Comment by gmavenis** [comment]
Thank you for supporting.
But I have problem when copy to other module (same app name, package name)

W/nend_SDK: net.nend.android.b.a:
                                                                      [AE821] Failed to parse response.
                                                                      net.nend.android.af: [AE815] Ad status is invalid. Ad status : 501, Message : [DeliveryBase::__returnEmpty](172.17.144.112) Cannot display ads
                                                                          at net.nend.android.b.a(AbsNendAdResponseParser.java:66)
                                                                          at net.nend.android.f.a(NendAd.java:239)
                                                                          at net.nend.android.f.makeResponse(NendAd.java:17)
                                                                          at net.nend.android.i$e.call(NendAdExecutor.java:110)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

#                                                                           at java.lang.Thread.run(Thread.java:818)

If I use Nend demo key, it is working.
But with my Nend key, old source ok, new source not working with above logs.

**Comment by ghost** [comment]
@gmavenis 
Thank you for your reply.

> If I use Nend demo key, it is working. 
> But with my Nend key, old source ok, new source not working with above logs.

Your implementation probably not wrong.

Please check below.
- Is the applicable ad spot set to active?
- Is the ID correctly imputed on the applicable ad spot?
  - Is the platform correct? (Please make sure you are not using ad ID for iOS on Android ad spot)  
  - Is the ad format correct? (Please make sure you are not using ID for banner ad on interstitial ad spot)
- Is the language setting of the device and simulator are set to Japanese?  
  - If the language setting is not Japanese, a receiving error might appear as there are not enough ad inventories to deliver.

If the problem is not solved after checking above, please inquire from [here](https://www.nend.net/inquiries/form/).

※ When contacting us, we hope you can send us the following information along.
- Media registration name
- ApiKey and SpotID
- SDK version
- crash logs, etc.

**Comment by gmavenis** [comment]
<net.nend.android.NendAdView
                android:id="@+id/nendAdView"
                NendAdjustSize="true"
                NendApiKey="d0c86e238f1154260e7b93c901a5afa36f0ba99f"
                NendSpotId="624212"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:gravity="center" />

# 
1. Same layout
2. Same Android source (2 module in Android studio)

# 3. Same device

How to do "Is the applicable ad spot set to active?"

**Comment by ghost** [comment]
@gmavenis 
Thank you for your reply.
We could show banner ad by use your Api Key and Spot ID.

> How to do "Is the applicable ad spot set to active?"  

We checked your ad spot and it was already active.

Please check again this.

> > - Is the language setting of the device and simulator are set to Japanese?  
> >   - If the language setting is not Japanese, a receiving error might appear as there are not enough ad inventories to deliver.

Regards

**Comment by gmavenis** [comment]
Thank you,

I have to set Locale:
Locale.setDefault(Locale.JAPANESE);

**Comment by gmavenis** [comment]
In wiki, you should say that.
Thanks

**Comment by ghost** [comment]
@gmavenis 
Thank you for your reply.

> - Is the language setting of the device and simulator are set to Japanese?  
>   - If the language setting is not Japanese, a receiving error might appear as there are not enough ad inventories to deliver.

This means device (or emulator)'s  language setting. It is not about setting on Source Code.
To set up the device's Language, do the following:
[ Settings > Language & input > Language ]

And, english wiki will be soon update. Please wait for a while.

Regards
